[workspace]
members = [
  ".",
  "crates/ast",
  "crates/lexer",
  "crates/parser",
  "crates/stdlib",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
thiserror = "1"
rustyline = "13"

[package]
name = "vexcore"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
lexer = { path = "crates/lexer" }
parser = { path = "crates/parser" }
ast = { path = "crates/ast" }
stdlib = { path = "crates/stdlib" }
